# Generated by Django 2.2.6 on 2019-11-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction', models.CharField(blank=True, max_length=255, null=True)),
                ('streaming', models.CharField(blank=True, max_length=255, null=True)),
                ('playstyle', models.CharField(blank=True, max_length=255, null=True)),
                ('usagepattern', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='dob of User'),
        ),
        migrations.AddField(
            model_name='user',
            name='face_data',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='face data of User'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='user',
            name='face_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='face id of User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name of User'),
        ),
    ]
